build:
  version: "2.0"

accounts:
  message: "Welcome to KiwixBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "simitha@kiwixbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371