apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb-deployment
  labels:
    app: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: accountsdb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: accountsdb
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  selector:
    app: accountsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
