apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb-deployment
  labels:
    app: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: cardsdb
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  selector:
    app: cardsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
